[build]
    command = "npm run build"
    publish = "dist"
    environment = {
        NODE_VERSION = "12"
    }

[[redirects]]
    from = "/p/a-text-based-game/"
    to = "https://mm-text.glitch.me/?ref=xyz-redir"
    status = 301

[[redirects]]
    from = "/*"
    to = "/404/"
    status = 404
